version: '2'
services:
  base:
    image: node:11
    volumes:
      - .:/usr/src/services
    working_dir: /usr/src/services
  install:
    extends:
      service: base
    command: npm install
  watch:
    extends:
      service: base
    ports:
      - 8080:8080
    command: npm run watch
  start:
    extends:
      service: base
    ports:
      - 8080:8080
    command: npm run start
